### ISSUE TITLE
슬랙 리뷰어 태그 이슈

### ISSUE THREAD

**Issue by zi-gae** [Lubycon/divid-front#4]
https://github.com/Lubycon/ourney-front/blob/dd05dd19873ce197625c30c4fda3c27b63a140de/.github/workflows/slack-noti.yml#L14

`SLACK_BOT_TOKEN ` => `LUBYCON_SLACK_BOT_TOKEN` 으로 변경하시면 동작 할 듯합니당!

**Comment by MiaJLee** [comment]
앗 이런 실수를,, 감사합니다 건우님!!!!!!!!!
